[package]
name = "admin/point-break"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.4" # GUI framework
promise = "evaera/promise@4.0.0" # Self-explanatory
janitor = "howmanysmall/janitor@1.15.1" # Garbage collection
knit = "sleitnick/knit@1.4.7" # Service framework