[package]
name = "admin/point-break"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.7" # Service framework
Promise = "evaera/promise@4.0.0" # Self-explanatory
Janitor = "howmanysmall/janitor@1.15.1" # Garbage collection
Sift = "csqrl/sift@=0.0.1" # Array manipulation
Roact = "roblox/roact@1.4.4" # GUI framework